openapi: 3.1.0
info:
  title: Nutrition Logger API
  version: "2.0.0"
  description: >-
    API for recording and retrieving detailed nutrition entries stored in
    a Notion database. All endpoints require an `x-api-key` header.
servers:
  - url: https://notionuploader-groa.onrender.com
paths:
  /v2/nutrition-entries:
    post:
      summary: Create nutrition entry
      description: >-
        Record a new food item and its macronutrient breakdown in the Notion
        database.
      operationId: createNutritionEntry
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NutritionEntry"
      responses:
        "201":
          description: Entry successfully created.
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    example: success
  /v2/nutrition-entries/daily/{date}:
    get:
      summary: List nutrition entries for a specific day
      description: >-
        Retrieve every nutrition entry recorded on a specific calendar day.
      operationId: listDailyNutritionEntries
      security:
        - ApiKeyAuth: []
      parameters:
        - name: date
          in: path
          required: true
          description: Date to fetch in YYYY-MM-DD format.
          schema:
            type: string
      responses:
        "200":
          description: Array of nutrition entries for the requested day.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NutritionEntry"
  /v2/nutrition-entries/period:
    get:
      summary: List nutrition entries within a date range
      description: >-
        Retrieve all nutrition entries between two dates, inclusive.
      operationId: listNutritionEntriesByPeriod
      security:
        - ApiKeyAuth: []
      parameters:
        - name: start_date
          in: query
          required: true
          description: Start date (inclusive) in YYYY-MM-DD format.
          schema:
            type: string
        - name: end_date
          in: query
          required: true
          description: End date (inclusive) in YYYY-MM-DD format.
          schema:
            type: string
      responses:
        "200":
          description: Array of nutrition entries within the specified period.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NutritionEntry"
  /v2/api-schema:
    get:
      summary: Retrieve API schema
      description: Return the OpenAPI specification for this API version.
      operationId: getApiSchema
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OpenAPI schema document.
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    NutritionEntry:
      type: object
      required:
        - food_item
        - date
        - calories
        - protein_g
        - carbs_g
        - fat_g
        - meal_type
        - notes
      properties:
        food_item:
          type: string
          description: Name of the food item consumed.
        date:
          type: string
          description: Date of consumption in YYYY-MM-DD format.
        calories:
          type: integer
          description: Total calories for the food item.
        protein_g:
          type: number
          description: Protein content in grams.
        carbs_g:
          type: number
          description: Carbohydrate content in grams.
        fat_g:
          type: number
          description: Fat content in grams.
        meal_type:
          type: string
          description: Type of meal when the food was eaten.
          enum:
            - Breakfast
            - Lunch
            - Dinner
            - Snack
            - Pre-workout
            - Post-workout
        notes:
          type: string
          description: Additional notes or details about the entry.
security:
  - ApiKeyAuth: []
