"""Quality gate for coverage thresholds."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Validate coverage.json output ensuring the total coverage and each file "
            "meet the configured thresholds."
        )
    )
    parser.add_argument(
        "path",
        type=Path,
        help="Path to the JSON coverage report generated by pytest-cov.",
    )
    parser.add_argument(
        "--total-threshold",
        type=float,
        default=90.0,
        help="Minimum overall coverage percentage required (default: 90).",
    )
    parser.add_argument(
        "--per-file-threshold",
        type=float,
        default=75.0,
        help="Minimum coverage percentage for individual files (default: 75).",
    )
    return parser.parse_args()


def load_coverage_data(path: Path) -> Dict[str, object]:
    if not path.exists():
        raise FileNotFoundError(
            f"Coverage report '{path}' not found. Run pytest with --cov-report=json first."
        )

    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def iter_file_coverages(data: Dict[str, object]) -> Iterable[Tuple[str, float]]:
    files = data.get("files", {})
    for name, file_data in files.items():
        summary = file_data.get("summary", {})
        percent = summary.get("percent_covered")
        if percent is None:
            continue
        yield name, float(percent)


def main() -> int:
    args = parse_args()
    data = load_coverage_data(args.path)

    total = float(data.get("totals", {}).get("percent_covered", 0.0))
    errors: list[str] = []

    if total < args.total_threshold:
        errors.append(
            f"Total coverage {total:.2f}% is below required {args.total_threshold:.2f}%"
        )

    for name, percent in iter_file_coverages(data):
        if percent < args.per_file_threshold:
            errors.append(
                f"{name} coverage {percent:.2f}% is below required "
                f"{args.per_file_threshold:.2f}%"
            )

    if errors:
        for message in errors:
            print(message)
        return 1

    print(
        f"Coverage gate passed: total {total:.2f}% >= {args.total_threshold:.2f}% "
        f"and all files >= {args.per_file_threshold:.2f}%"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - script entrypoint
    raise SystemExit(main())
